#define ELSE_KEYWORD 1
#define IF_KEYWORD 2
#define INT_KEYWORD 3
#define RETURN_KEYWORD 4
#define VOID_KEYWORD 5
#define WHILE_KEYWORD 6
#define PLUS 7
#define MINUS 8
#define MULT 9
#define DIV 10
#define LCHEVRON_EQ 11
#define LCHEVRON 12
#define RCHEVRON_EQ 13
#define RCHEVRON 14
#define DBL_EQ 15
#define NEQ 16
#define EQ 17
#define SCOLON 18
#define COMMA 19
#define LBRACE 20
#define RBRACE 21
#define LPAREN 22
#define RPAREN 23
#define LBRACK 24
#define RBRACK 25
#define ID 26
#define NUM 27
